// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkjeloaxsxznhulyzzwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFramVsb2F4c3h6bmh1bHl6endmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTkxNTksImV4cCI6MjA2ODQzNTE1OX0.XiiP5CQ4I6M-afMC6wpYQEaXI-hV3-avf3nv7NbLfhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});